# 摘要說明

在這個範例中，共啟動了4個執行緒 (一個主執行緒，3個自訂執行緒)，當執行緒內的執行方法發生了例外異常，是會造成整個處理程序意外終止；其中，在執行緒2內，我們有捕捉例外異常，並且還原內容與釋放資源，因此，執行緒2，不會造成處理程序意外終止與造成處理程序不穩定。

其中，在執行緒2內，我們有捕捉例外異常，並且還原內容與釋放資源，因此，執行緒2，不會造成處理程序意外終止與造成處理程序不穩定

## 練習說明

* 請實際執行這個範例程式
  * 看看會發生甚麼樣的結果，整個處理程序可以正常執行完成嗎？
  

  